
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/tmp/pip-build-env-8qvxcm7b/overlay/lib/python3.10/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 4.18.0-477.86.1.el8_8.x86_64 - x86_64
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/projects/bdjx/hxia3/softlinks/.conda/envs/rag/lib/python3.10/site-packages/cmake/data/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 4.18.0-477.86.1.el8_8.x86_64 - x86_64
...
