# SPDX-License-Identifier: Apache-2.0

"""
Add lazy attention support to the BlockPool.
"""
from collections import defaultdict
from collections.abc import Iterable
from typing import Callable, Optional

from vllm.logger import init_logger
from vllm.v1.core.kv_cache_utils import (BlockHashType, FreeKVCacheBlockQueue,
                                         KVCacheBlock,
                                         generate_block_hash_extra_keys,
                                         hash_block_tokens)
from minidrag.request import Request

logger = init_logger(__name__)


# class BlockPool:

def cache_full_blocks(
    self,
    request: Request,
    blocks: list[KVCacheBlock],
    block_hashes: list[BlockHashType],
    num_cached_blocks: int,
    num_full_blocks: int,
    block_size: int,
    hash_fn: Callable,
) -> None:
    """Cache a list of full blocks for prefix caching.
    This function takes a list of blocks that will have their block hash
    metadata to be updated and cached. Given a request, it computes the
    block hashes for the blocks starting from `num_cached_blocks` to
    `num_full_blocks`, updating the metadata for each block
    and caching them in the `cached_block_hash_to_block`.

    Args:
        request: The request to cache the blocks.
        blocks: All blocks in the request.
        block_hashes: Block hashes of the blocks in the request. Note that
        this list may be shorter than the blocks list. In this case the
        missed block hash will be computed in this function.
        num_cached_blocks: The number of blocks that are already cached.
        num_full_blocks: The number of blocks that are full and should
            be cached after this function.
        block_size: Number of tokens in each block.
        hash_fn: The hash function to use for block hashes.
    """
    if num_cached_blocks == num_full_blocks:
        return
    new_full_blocks = blocks[num_cached_blocks:num_full_blocks]
    assert len(block_hashes) >= num_cached_blocks
    new_block_hashes = block_hashes[num_cached_blocks:]

    # Update the new blocks with the block hashes through the chain.
    if num_cached_blocks == 0:
        prev_block_hash_value = None
        # Lazy attention, if one req has documents, it is lazy
        # The query part attends all documents, so the first block is 
        # the document sequence hash.
        if request.has_documents:
            # The first block is the document sequence hash.
            prev_block_hash_value = request.document_seq_hash
    else:
        prev_block = blocks[num_cached_blocks - 1]
        assert prev_block.block_hash is not None
        prev_block_hash_value = prev_block.block_hash.hash_value

    for i, blk in enumerate(new_full_blocks):
        assert blk.block_hash is None

        if i < len(new_block_hashes):
            # The block hash may already be computed in
            # "get_computed_blocks" if the tokens are not generated by
            # this request (either the prompt tokens or the previously
            # generated tokens with preemption). In this case we simply
            # reuse the block hash.
            block_hash = new_block_hashes[i]
        else:
            # Otherwise compute the block hash and cache it in the request
            # in case it will be preempted in the future.
            blk_idx = num_cached_blocks + i
            start_token_idx = blk_idx * block_size
            end_token_idx = (blk_idx + 1) * block_size
            block_tokens = request.all_token_ids[
                start_token_idx:end_token_idx]
            assert len(block_tokens) == block_size, (
                f"Expected {block_size} tokens, got "
                f"{len(block_tokens)} at {blk_idx}th block for request "
                f"{request.request_id}({request})")

            # Generate extra keys for multi-modal inputs. Note that since
            # we reach to this branch only when the block is completed with
            # generated tokens, we only need to consider the last mm input.
            extra_keys, _ = generate_block_hash_extra_keys(
                request, start_token_idx, end_token_idx, -1)

            # Compute the hash of the current block.
            block_hash = hash_block_tokens(hash_fn, prev_block_hash_value,
                                           block_tokens, extra_keys)
            block_hashes.append(block_hash)
        # Update and added the full block to the cache.
        blk.block_hash = block_hash
        self.cached_block_hash_to_block[block_hash][blk.block_id] = blk
        prev_block_hash_value = block_hash.hash_value

def cache_full_blocks_docs(
    self,
    request: Request,
    blocks_docs: list[list[KVCacheBlock]],
    block_hashes_docs: list[list[BlockHashType]],
    num_cached_blocks_docs: list[int],
    num_full_blocks_docs: list[int],
    block_size: int,
    hash_fn: Callable,
) -> None:
    """
    Cache a list of full blocks for prefix caching.

    This is a variant of cache_full_blocks, but for documents.
    The document blocks are cached separately.
    """
    assert request.has_documents
    if num_cached_blocks_docs == num_full_blocks_docs:
        return
    # Need to cache the blocks for documents
    num_docs = len(request.documents_token_ids)
    for doc_idx in range(num_docs):
        num_cached_blocks_doc = num_cached_blocks_docs[doc_idx]
        num_full_blocks_doc = num_full_blocks_docs[doc_idx]
        new_full_blocks_doc = \
            blocks_docs[doc_idx][num_cached_blocks_doc:
                                num_full_blocks_doc]
        new_block_hashes_doc = \
            block_hashes_docs[doc_idx][num_cached_blocks_doc:]
        if num_cached_blocks_doc == 0:
            prev_block_hash_value = None
        else:
            prev_block = blocks_docs[doc_idx][num_cached_blocks_doc - 1]
            assert prev_block.block_hash is not None
            prev_block_hash_value = prev_block.block_hash.hash_value
        for i, blk in enumerate(new_full_blocks_doc):
            assert blk.block_hash is None
            if i < len(new_block_hashes_doc):
                block_hash = new_block_hashes_doc[i]
            else:
                # assert False, (
                #     f"Document block will not created during generation ")
                blk_idx = num_cached_blocks_doc + i
                start_token_idx = blk_idx * block_size
                end_token_idx = (blk_idx + 1) * block_size
                block_tokens = request.documents_token_ids[doc_idx][
                    start_token_idx:end_token_idx]
                block_hash = hash_block_tokens(hash_fn, prev_block_hash_value,
                                block_tokens, extra_keys=None)
                block_hashes_docs[doc_idx].append(block_hash)
            # Update and added the full block to the cache.
            blk.block_hash = block_hash
            self.cached_block_hash_to_block[block_hash][blk.block_id] = blk
            prev_block_hash_value = block_hash.hash_value